# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_dockeditor.ui'
#
# Created: Mon Jan 12 13:05:53 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockEditor(object):
    def setupUi(self, DockEditor):
        DockEditor.setObjectName(_fromUtf8("DockEditor"))
        DockEditor.resize(400, 1271)
        DockEditor.setMinimumSize(QtCore.QSize(400, 600))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.newGroupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.newGroupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.newGroupBox.setTitle(_fromUtf8(""))
        self.newGroupBox.setObjectName(_fromUtf8("newGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.newGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.pandidLabel = QtGui.QLabel(self.newGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pandidLabel.setFont(font)
        self.pandidLabel.setObjectName(_fromUtf8("pandidLabel"))
        self.gridLayout_2.addWidget(self.pandidLabel, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.newGroupBox)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 3)
        self.newPandButton = QtGui.QPushButton(self.newGroupBox)
        self.newPandButton.setObjectName(_fromUtf8("newPandButton"))
        self.gridLayout_2.addWidget(self.newPandButton, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.newGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.statusNieuwLabel = QtGui.QLabel(self.newGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusNieuwLabel.setFont(font)
        self.statusNieuwLabel.setObjectName(_fromUtf8("statusNieuwLabel"))
        self.gridLayout_2.addWidget(self.statusNieuwLabel, 2, 0, 1, 3)
        self.verticalLayout.addWidget(self.newGroupBox)
        self.editGroupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.editGroupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.editGroupBox.setTitle(_fromUtf8(""))
        self.editGroupBox.setFlat(False)
        self.editGroupBox.setCheckable(False)
        self.editGroupBox.setChecked(False)
        self.editGroupBox.setObjectName(_fromUtf8("editGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.editGroupBox)
        self.gridLayout_3.setMargin(10)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verwijderWidget = QtGui.QWidget(self.editGroupBox)
        self.verwijderWidget.setEnabled(True)
        self.verwijderWidget.setObjectName(_fromUtf8("verwijderWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.verwijderWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.deleteCheckBox = QtGui.QCheckBox(self.verwijderWidget)
        self.deleteCheckBox.setObjectName(_fromUtf8("deleteCheckBox"))
        self.horizontalLayout_4.addWidget(self.deleteCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.deleteButton = QtGui.QPushButton(self.verwijderWidget)
        self.deleteButton.setEnabled(False)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_4.addWidget(self.deleteButton)
        self.gridLayout_3.addWidget(self.verwijderWidget, 6, 0, 2, 1)
        self.saveWidget = QtGui.QWidget(self.editGroupBox)
        self.saveWidget.setObjectName(_fromUtf8("saveWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.saveWidget)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.saveWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.actionButtonBox = QtGui.QDialogButtonBox(self.saveWidget)
        self.actionButtonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Dutch, QtCore.QLocale.Netherlands))
        self.actionButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.actionButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Abort|QtGui.QDialogButtonBox.Save)
        self.actionButtonBox.setObjectName(_fromUtf8("actionButtonBox"))
        self.horizontalLayout_5.addWidget(self.actionButtonBox)
        self.gridLayout_3.addWidget(self.saveWidget, 2, 0, 1, 1)
        self.detailsGroupBox = QtGui.QGroupBox(self.editGroupBox)
        self.detailsGroupBox.setMinimumSize(QtCore.QSize(0, 340))
        self.detailsGroupBox.setTitle(_fromUtf8(""))
        self.detailsGroupBox.setObjectName(_fromUtf8("detailsGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.detailsGroupBox)
        self.gridLayout.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.monitoringObjTekst = QtGui.QLineEdit(self.detailsGroupBox)
        self.monitoringObjTekst.setEnabled(False)
        self.monitoringObjTekst.setObjectName(_fromUtf8("monitoringObjTekst"))
        self.gridLayout.addWidget(self.monitoringObjTekst, 17, 1, 1, 1)
        self.typefundLabel = QtGui.QLabel(self.detailsGroupBox)
        self.typefundLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.typefundLabel.setObjectName(_fromUtf8("typefundLabel"))
        self.gridLayout.addWidget(self.typefundLabel, 23, 0, 1, 1)
        self.typefundCombo = QtGui.QComboBox(self.detailsGroupBox)
        self.typefundCombo.setMinimumSize(QtCore.QSize(0, 21))
        self.typefundCombo.setEditable(True)
        self.typefundCombo.setObjectName(_fromUtf8("typefundCombo"))
        self.gridLayout.addWidget(self.typefundCombo, 23, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.idText = QtGui.QLineEdit(self.detailsGroupBox)
        self.idText.setEnabled(False)
        self.idText.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idText.setFont(font)
        self.idText.setText(_fromUtf8(""))
        self.idText.setReadOnly(True)
        self.idText.setObjectName(_fromUtf8("idText"))
        self.horizontalLayout.addWidget(self.idText)
        self.idButton = QtGui.QPushButton(self.detailsGroupBox)
        self.idButton.setMinimumSize(QtCore.QSize(0, 21))
        self.idButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/funderingsherstel/icons/zoomin.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.idButton.setIcon(icon)
        self.idButton.setObjectName(_fromUtf8("idButton"))
        self.horizontalLayout.addWidget(self.idButton)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.bouwjaarText = QtGui.QLineEdit(self.detailsGroupBox)
        self.bouwjaarText.setEnabled(False)
        self.bouwjaarText.setMinimumSize(QtCore.QSize(0, 21))
        self.bouwjaarText.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bouwjaarText.setReadOnly(True)
        self.bouwjaarText.setObjectName(_fromUtf8("bouwjaarText"))
        self.gridLayout.addWidget(self.bouwjaarText, 11, 1, 1, 1)
        self.richtlijnCombo = QtGui.QComboBox(self.detailsGroupBox)
        self.richtlijnCombo.setMinimumSize(QtCore.QSize(0, 21))
        self.richtlijnCombo.setEditable(True)
        self.richtlijnCombo.setObjectName(_fromUtf8("richtlijnCombo"))
        self.gridLayout.addWidget(self.richtlijnCombo, 25, 1, 1, 1)
        self.line = QtGui.QFrame(self.detailsGroupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 15, 0, 1, 2)
        self.kwaliteitsklasseCombo = QtGui.QComboBox(self.detailsGroupBox)
        self.kwaliteitsklasseCombo.setMinimumSize(QtCore.QSize(0, 26))
        self.kwaliteitsklasseCombo.setObjectName(_fromUtf8("kwaliteitsklasseCombo"))
        self.kwaliteitsklasseCombo.addItem(_fromUtf8(""))
        self.kwaliteitsklasseCombo.addItem(_fromUtf8(""))
        self.kwaliteitsklasseCombo.addItem(_fromUtf8(""))
        self.kwaliteitsklasseCombo.addItem(_fromUtf8(""))
        self.kwaliteitsklasseCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.kwaliteitsklasseCombo, 13, 1, 1, 1)
        self.onderzochtJaarSpinBox = QtGui.QSpinBox(self.detailsGroupBox)
        self.onderzochtJaarSpinBox.setMinimumSize(QtCore.QSize(0, 24))
        self.onderzochtJaarSpinBox.setSpecialValueText(_fromUtf8(""))
        self.onderzochtJaarSpinBox.setSuffix(_fromUtf8(""))
        self.onderzochtJaarSpinBox.setPrefix(_fromUtf8(""))
        self.onderzochtJaarSpinBox.setMinimum(1900)
        self.onderzochtJaarSpinBox.setMaximum(2050)
        self.onderzochtJaarSpinBox.setProperty("value", 1900)
        self.onderzochtJaarSpinBox.setObjectName(_fromUtf8("onderzochtJaarSpinBox"))
        self.gridLayout.addWidget(self.onderzochtJaarSpinBox, 12, 1, 1, 1)
        self.hersteldJaarSpinBox = QtGui.QSpinBox(self.detailsGroupBox)
        self.hersteldJaarSpinBox.setEnabled(True)
        self.hersteldJaarSpinBox.setMinimumSize(QtCore.QSize(0, 24))
        self.hersteldJaarSpinBox.setWrapping(False)
        self.hersteldJaarSpinBox.setSpecialValueText(_fromUtf8(""))
        self.hersteldJaarSpinBox.setMinimum(1900)
        self.hersteldJaarSpinBox.setMaximum(2050)
        self.hersteldJaarSpinBox.setProperty("value", 1900)
        self.hersteldJaarSpinBox.setObjectName(_fromUtf8("hersteldJaarSpinBox"))
        self.gridLayout.addWidget(self.hersteldJaarSpinBox, 14, 1, 1, 1)
        self.opmerkingLabel = QtGui.QLabel(self.detailsGroupBox)
        self.opmerkingLabel.setObjectName(_fromUtf8("opmerkingLabel"))
        self.gridLayout.addWidget(self.opmerkingLabel, 26, 0, 1, 1)
        self.projectCombo = QtGui.QComboBox(self.detailsGroupBox)
        self.projectCombo.setMinimumSize(QtCore.QSize(0, 21))
        self.projectCombo.setEditable(True)
        self.projectCombo.setObjectName(_fromUtf8("projectCombo"))
        self.gridLayout.addWidget(self.projectCombo, 24, 1, 1, 1)
        self.kwaliteitsklasseLabel = QtGui.QLabel(self.detailsGroupBox)
        self.kwaliteitsklasseLabel.setObjectName(_fromUtf8("kwaliteitsklasseLabel"))
        self.gridLayout.addWidget(self.kwaliteitsklasseLabel, 13, 0, 1, 1)
        self.richtlijnLabel = QtGui.QLabel(self.detailsGroupBox)
        self.richtlijnLabel.setObjectName(_fromUtf8("richtlijnLabel"))
        self.gridLayout.addWidget(self.richtlijnLabel, 25, 0, 1, 1)
        self.renbLabel = QtGui.QLabel(self.detailsGroupBox)
        self.renbLabel.setObjectName(_fromUtf8("renbLabel"))
        self.gridLayout.addWidget(self.renbLabel, 24, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.detailsGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.bouwjaarLabel = QtGui.QLabel(self.detailsGroupBox)
        self.bouwjaarLabel.setObjectName(_fromUtf8("bouwjaarLabel"))
        self.gridLayout.addWidget(self.bouwjaarLabel, 11, 0, 1, 1)
        self.inonderzoekCheckBox = QtGui.QCheckBox(self.detailsGroupBox)
        self.inonderzoekCheckBox.setMinimumSize(QtCore.QSize(0, 24))
        self.inonderzoekCheckBox.setObjectName(_fromUtf8("inonderzoekCheckBox"))
        self.gridLayout.addWidget(self.inonderzoekCheckBox, 19, 0, 1, 2)
        self.hersteldCheckBox = QtGui.QCheckBox(self.detailsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.hersteldCheckBox.sizePolicy().hasHeightForWidth())
        self.hersteldCheckBox.setSizePolicy(sizePolicy)
        self.hersteldCheckBox.setMinimumSize(QtCore.QSize(0, 24))
        self.hersteldCheckBox.setObjectName(_fromUtf8("hersteldCheckBox"))
        self.gridLayout.addWidget(self.hersteldCheckBox, 14, 0, 1, 1)
        self.onderzochtCheckBox = QtGui.QCheckBox(self.detailsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.onderzochtCheckBox.sizePolicy().hasHeightForWidth())
        self.onderzochtCheckBox.setSizePolicy(sizePolicy)
        self.onderzochtCheckBox.setMinimumSize(QtCore.QSize(0, 24))
        self.onderzochtCheckBox.setObjectName(_fromUtf8("onderzochtCheckBox"))
        self.gridLayout.addWidget(self.onderzochtCheckBox, 12, 0, 1, 1)
        self.idLabel = QtGui.QLabel(self.detailsGroupBox)
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.gridLayout.addWidget(self.idLabel, 6, 0, 1, 1)
        self.opmerkingText = QtGui.QTextEdit(self.detailsGroupBox)
        self.opmerkingText.setMinimumSize(QtCore.QSize(0, 21))
        self.opmerkingText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.opmerkingText.setObjectName(_fromUtf8("opmerkingText"))
        self.gridLayout.addWidget(self.opmerkingText, 26, 1, 1, 1)
        self.statusLabel = QtGui.QLabel(self.detailsGroupBox)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.gridLayout.addWidget(self.statusLabel, 7, 0, 1, 1)
        self.statusText = QtGui.QLineEdit(self.detailsGroupBox)
        self.statusText.setEnabled(False)
        self.statusText.setMinimumSize(QtCore.QSize(0, 21))
        self.statusText.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusText.setAutoFillBackground(False)
        self.statusText.setText(_fromUtf8(""))
        self.statusText.setReadOnly(True)
        self.statusText.setObjectName(_fromUtf8("statusText"))
        self.gridLayout.addWidget(self.statusText, 7, 1, 1, 1)
        self.droogstandCheckBox = QtGui.QCheckBox(self.detailsGroupBox)
        self.droogstandCheckBox.setMinimumSize(QtCore.QSize(0, 24))
        self.droogstandCheckBox.setObjectName(_fromUtf8("droogstandCheckBox"))
        self.gridLayout.addWidget(self.droogstandCheckBox, 18, 0, 1, 1)
        self.handhavingCheckBox = QtGui.QCheckBox(self.detailsGroupBox)
        self.handhavingCheckBox.setEnabled(False)
        self.handhavingCheckBox.setMinimumSize(QtCore.QSize(0, 24))
        self.handhavingCheckBox.setObjectName(_fromUtf8("handhavingCheckBox"))
        self.gridLayout.addWidget(self.handhavingCheckBox, 17, 0, 1, 1)
        self.gridLayout_3.addWidget(self.detailsGroupBox, 5, 0, 1, 1)
        self.widget = QtGui.QWidget(self.editGroupBox)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verseonLinkButton = QtGui.QCommandLinkButton(self.widget)
        self.verseonLinkButton.setEnabled(True)
        self.verseonLinkButton.setMinimumSize(QtCore.QSize(0, 0))
        self.verseonLinkButton.setObjectName(_fromUtf8("verseonLinkButton"))
        self.gridLayout_4.addWidget(self.verseonLinkButton, 1, 0, 1, 1)
        self.adresLinkButton = QtGui.QCommandLinkButton(self.widget)
        self.adresLinkButton.setMinimumSize(QtCore.QSize(0, 0))
        self.adresLinkButton.setObjectName(_fromUtf8("adresLinkButton"))
        self.gridLayout_4.addWidget(self.adresLinkButton, 0, 0, 1, 1)
        self.lkiLinkButton = QtGui.QCommandLinkButton(self.widget)
        self.lkiLinkButton.setEnabled(True)
        self.lkiLinkButton.setObjectName(_fromUtf8("lkiLinkButton"))
        self.gridLayout_4.addWidget(self.lkiLinkButton, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 3, 0, 2, 1)
        self.verticalLayout.addWidget(self.editGroupBox)
        self.errorFrame = QtGui.QFrame(self.dockWidgetContents)
        self.errorFrame.setEnabled(True)
        self.errorFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.errorFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.errorFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.errorFrame.setObjectName(_fromUtf8("errorFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.errorFrame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.errorFrame)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.errorFrame)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        DockEditor.setWidget(self.dockWidgetContents)
        self.pandidLabel.setBuddy(self.newPandButton)
        self.opmerkingLabel.setBuddy(self.opmerkingText)
        self.kwaliteitsklasseLabel.setBuddy(self.kwaliteitsklasseCombo)
        self.richtlijnLabel.setBuddy(self.richtlijnCombo)
        self.renbLabel.setBuddy(self.projectCombo)
        self.bouwjaarLabel.setBuddy(self.bouwjaarText)
        self.idLabel.setBuddy(self.idText)
        self.statusLabel.setBuddy(self.statusText)

        self.retranslateUi(DockEditor)
        QtCore.QObject.connect(self.hersteldCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.hersteldJaarSpinBox.setVisible)
        QtCore.QObject.connect(self.onderzochtCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.onderzochtJaarSpinBox.setVisible)
        QtCore.QObject.connect(self.deleteCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.deleteButton.setEnabled)
        QtCore.QObject.connect(self.onderzochtCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.kwaliteitsklasseLabel.setVisible)
        QtCore.QObject.connect(self.onderzochtCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.kwaliteitsklasseCombo.setVisible)
        QtCore.QObject.connect(self.hersteldCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.kwaliteitsklasseLabel.setDisabled)
        QtCore.QObject.connect(self.hersteldCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.kwaliteitsklasseCombo.setDisabled)
        QtCore.QObject.connect(self.hersteldCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.onderzochtCheckBox.setDisabled)
        QtCore.QObject.connect(self.hersteldCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.onderzochtJaarSpinBox.setDisabled)
        QtCore.QObject.connect(self.handhavingCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.monitoringObjTekst.setVisible)
        QtCore.QMetaObject.connectSlotsByName(DockEditor)
        DockEditor.setTabOrder(self.idButton, self.bouwjaarText)
        DockEditor.setTabOrder(self.bouwjaarText, self.onderzochtCheckBox)
        DockEditor.setTabOrder(self.onderzochtCheckBox, self.onderzochtJaarSpinBox)
        DockEditor.setTabOrder(self.onderzochtJaarSpinBox, self.hersteldCheckBox)
        DockEditor.setTabOrder(self.hersteldCheckBox, self.hersteldJaarSpinBox)
        DockEditor.setTabOrder(self.hersteldJaarSpinBox, self.inonderzoekCheckBox)
        DockEditor.setTabOrder(self.inonderzoekCheckBox, self.projectCombo)
        DockEditor.setTabOrder(self.projectCombo, self.richtlijnCombo)
        DockEditor.setTabOrder(self.richtlijnCombo, self.opmerkingText)
        DockEditor.setTabOrder(self.opmerkingText, self.deleteCheckBox)
        DockEditor.setTabOrder(self.deleteCheckBox, self.deleteButton)
        DockEditor.setTabOrder(self.deleteButton, self.actionButtonBox)
        DockEditor.setTabOrder(self.actionButtonBox, self.newPandButton)
        DockEditor.setTabOrder(self.newPandButton, self.adresLinkButton)
        DockEditor.setTabOrder(self.adresLinkButton, self.kwaliteitsklasseCombo)
        DockEditor.setTabOrder(self.kwaliteitsklasseCombo, self.idText)

    def retranslateUi(self, DockEditor):
        DockEditor.setWindowTitle(_translate("DockEditor", "Funderingsherstel Zaanstad", None))
        self.label_4.setText(_translate("DockEditor", "<html><head/><body><p><b><span style=\" font-size:20pt; font-weight:600;\">Funderingsherstel</span></b></p><p>Klik in de kaart om info op te vragen en gegevens te muteren.</p></body></html>", None))
        self.pandidLabel.setText(_translate("DockEditor", "pandidLabel", None))
        self.label_2.setText(_translate("DockEditor", "Voor dit BAG object zijn nog geen funderingsgegevens opgeslagen:", None))
        self.newPandButton.setText(_translate("DockEditor", "Nieuw pand", None))
        self.label_5.setText(_translate("DockEditor", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#0080ff;\">Nieuw pand</span></p></body></html>", None))
        self.statusNieuwLabel.setText(_translate("DockEditor", "statusNieuwLabel", None))
        self.deleteCheckBox.setText(_translate("DockEditor", "Object verwijderen", None))
        self.deleteButton.setText(_translate("DockEditor", "Verwijderen", None))
        self.label_6.setText(_translate("DockEditor", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#408000;\">Pand bewerken</span></p></body></html>", None))
        self.typefundLabel.setText(_translate("DockEditor", "Type fundering", None))
        self.idButton.setToolTip(_translate("DockEditor", "Klik om in te zoomen naar pand", None))
        self.kwaliteitsklasseCombo.setItemText(0, _translate("DockEditor", "0", None))
        self.kwaliteitsklasseCombo.setItemText(1, _translate("DockEditor", "1", None))
        self.kwaliteitsklasseCombo.setItemText(2, _translate("DockEditor", "2", None))
        self.kwaliteitsklasseCombo.setItemText(3, _translate("DockEditor", "3", None))
        self.kwaliteitsklasseCombo.setItemText(4, _translate("DockEditor", "Onbekend", None))
        self.opmerkingLabel.setText(_translate("DockEditor", "Opmerking", None))
        self.kwaliteitsklasseLabel.setToolTip(_translate("DockEditor", "<html><head/><body><p>0   = Onbekend</p><p>1   = Ruim voldoende</p><p>2   = Voldoende</p><p>3   = Matig</p><p>3+ = Onvoldoende</p></body></html>", None))
        self.kwaliteitsklasseLabel.setText(_translate("DockEditor", "Kwaliteitsklasse", None))
        self.richtlijnLabel.setText(_translate("DockEditor", "Richtlijn", None))
        self.renbLabel.setText(_translate("DockEditor", "Project", None))
        self.label_3.setText(_translate("DockEditor", "<html><head/><body><p><span style=\" font-weight:600;\">Funderingsgegevens voor BAG object</span></p></body></html>", None))
        self.bouwjaarLabel.setText(_translate("DockEditor", "Bouwjaar", None))
        self.inonderzoekCheckBox.setText(_translate("DockEditor", "Pand in onderzoek", None))
        self.hersteldCheckBox.setText(_translate("DockEditor", "Hersteld jaar", None))
        self.onderzochtCheckBox.setText(_translate("DockEditor", "Pand onderzocht", None))
        self.idLabel.setText(_translate("DockEditor", "BAG id", None))
        self.statusLabel.setText(_translate("DockEditor", "Status", None))
        self.droogstandCheckBox.setText(_translate("DockEditor", "Droogstand", None))
        self.handhavingCheckBox.setText(_translate("DockEditor", "Monitoring", None))
        self.verseonLinkButton.setText(_translate("DockEditor", "Verseon gegevens", None))
        self.adresLinkButton.setToolTip(_translate("DockEditor", "Klik om adresgegevens op te vragen", None))
        self.adresLinkButton.setText(_translate("DockEditor", "adresLinkButton", None))
        self.lkiLinkButton.setText(_translate("DockEditor", "Kadaster gegevens", None))
        self.label.setText(_translate("DockEditor", "<html><head/><body><p><span style=\" color:#ff0000;\">Problemen geconstateerd, programma kan niet werken zonder de juiste kaartlagen.</span></p></body></html>", None))

import resources_rc
